services:
  db:
    image: postgres:16
    container_name: hvac_db
    environment:
      POSTGRES_USER: hvac
      POSTGRES_PASSWORD: hvacpass
      POSTGRES_DB: hvacdb
    ports:
      - "5433:5432"
    volumes:
      - hvac_pgdata:/var/lib/postgresql/data

volumes:
  hvac_pgdata: